---
title: "p8105_hw6_lq2250"
author: "Lanlan_Qing"
date: "2025-12-02"
output: github_document
---

## Initial Settings

```{r message = FALSE}
library(tidyverse)
library(modelr)
library(broom)
library(mgcv)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1
```{r}
# Import dataset and cleaning

homicide_df = 
  read_csv("data/homicide-data.csv") |> 
  mutate(city_state = str_c(city, ", ", state),
         resolved = as.numeric(disposition == "Closed by arrest")) |>
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")) |>
  mutate(victim_age = as.numeric(victim_age)) |>
  select(-city, -state, -disposition) |>
  relocate(city_state, .after = victim_sex) |>
  drop_na()

# Select race of white and black
homicide_race = homicide_df |>
  filter(victim_race %in% c("Black", "White"))

# Select city of Baltimore
baltimore_df = homicide_race |>
  filter(str_detect(city_state, "MD")) |>
  select(resolved, victim_age, victim_race, victim_sex)

# Logistic Linear Regression data of Baltimore
fit_logistic_md = 
  baltimore_df |> 
  glm(resolved ~ victim_age + victim_race + victim_sex, family = binomial(), data = _) |>
  broom::tidy(conf.int = TRUE)

# Logistic Linear Regression output and summary of Baltimore
fit_logistic_md |> 
  filter(str_detect(term, "Male")) |>
  mutate(OR = exp(estimate),
         OR_lower = exp(conf.low),
         OR_higher = exp(conf.high)) 
fit_logistic_md |> knitr::kable(digits = 3)
```

```{r}
# Fit for all cities
fit_logistic = homicide_race |> 
  select(city_state, resolved, victim_age, victim_race, victim_sex) |> 
  nest(data = -city_state) |>
  mutate(models = map(data, \(df)glm(resolved ~ victim_age + victim_race + victim_sex,family = binomial(), data = df)),
         results = map(models, \(mod)broom::tidy(mod, conf.int = TRUE))) |>
  select(-models, -data) |>
  unnest(results)

# Create dataframe with ORs and Cls
fit_logistic = 
  fit_logistic |> 
  filter(str_detect(term, "Male")) |>
  group_by(city_state) |>
  mutate(OR = exp(estimate),
         OR_lower = exp(conf.low),
         OR_higher = exp(conf.high)) |>
  select(city_state, OR, OR_lower, OR_higher)

fit_logistic |> knitr::kable()

# Create plot

fit_logistic |>
  ggplot(aes(x = fct_reorder(city_state, OR, .desc = TRUE),
             y = OR,
             ymin = OR_lower,
             ymax = OR_higher,
             color = ifelse(OR > 1, "OR > 1", "OR < 1"))) +
  geom_errorbar(width = 0.3,
                linewidth = 0.8,
                alpha = 0.5) +
  geom_point() +
  labs(
    x = "City",
    y = "Odds Ratio (OR)",
    title = "Odds of Homicide Case Resolution by Victim Sex (Male vs. Female)",
    color = "Effect Direction"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6))
```

